apiVersion: v1
kind: Service
metadata:
  name: cassandra
spec:
  ports:
    - port: 9042
      targetPort: 9042
  selector:
    app: cassandra
  type: ClusterIP

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: cassandra
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cassandra
  template:
    metadata:
      labels:
        app: cassandra
    spec:
      containers:
        - name: cassandra
          image: cassandra:4.1.5
          ports:
            - containerPort: 9042
      volumes:
        - name: script
          configMap:
            name: cassandra-init-config
            defaultMode: 0500
            items:
              - key: init-script.sh
                path: init-script.sh

---

apiVersion: batch/v1
kind: Job
metadata:
  name: cassandra-init
spec:
  template:
    spec:
      containers:
        - name: cassandra-init
          image: cassandra:4.1.5
          command: ["./scripts/init-script.sh"]
          volumeMounts:
            - name: script
              mountPath: "/scripts"

      volumes:
        - name: script
          configMap:
            name: cassandra-init-config
            defaultMode: 0500
            items:
              - key: init-script.sh
                path: init-script.sh
      restartPolicy: Never
  backoffLimit: 4