apiVersion: v1
kind: Service
metadata:
  name: pgadmin
spec:
  ports:
    - port: 8888
      targetPort: 80
  selector:
    app: pgadmin
  type: LoadBalancer  # Or LoadBalancer for external access

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgadmin
  labels:
    app: pgadmin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pgadmin
  template:
    metadata:
      labels:
        app: pgadmin
    spec:
      containers:
        - name: pgadmin
          image: dpage/pgadmin4
          ports:
            - containerPort: 80
          env:
            - name: PGADMIN_DEFAULT_EMAIL
              value: "db@db.com"
            - name: PGADMIN_DEFAULT_PASSWORD
              value: "pass"