apiVersion: v1
kind: Service
metadata:
  name: ui
spec:
  ports:
    - port: 4200
      targetPort: 4200
  selector:
    app: ui
  type: LoadBalancer

---
apiVersion: v1
kind: Pod
metadata:
  name: ui
  labels:
    app: ui
spec:
  containers:
  - name: ui
    image: ftndevops123/ui:develop
    ports:
    - containerPort: 4200
    volumeMounts:
    - name: ui
      mountPath: /usr/src/app/src/assets/environment.js
      subPath: environment.js
  volumes:
    - name: ui
      configMap:
        name: ui