apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
spec:
  ports:
    - port: 5672
      targetPort: 5672
  selector:
    app: rabbitmq
  type: ClusterIP

---
apiVersion: v1
kind: Pod
metadata:
  name: rabbitmq
  labels:
    app: rabbitmq
spec:
  containers:
  - name: rabbitmq
    image: rabbitmq:management
    ports:
    - name: "port1"
      containerPort: 5672
    - name: "port2"
      containerPort: 15672
    env:
    - name: RABBITMQ_DEFAULT_PASS
      value: devops
    - name: RABBITMQ_DEFAULT_USER
      value: devops
    - name: RABBITMQ_PASSWORD
      value: devops
    - name: RABBITMQ_USERNAME
      value: devops