apiVersion: v1
kind: Service
metadata:
  name: audit
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: audit
  type: ClusterIP

---
apiVersion: v1
kind: Pod
metadata:
  name: audit
  labels:
    app: audit
spec:
  containers:
  - name: audit
    image: ftndevops123/audit-service:1.0.0
    ports:
    - containerPort: 8080
    env:
    - name: CASSANDRA_URL
      value: cassandra
    - name: CASSANDRA_PORT
      value: '9042'
    - name: CASSANDRA_KEYSPACE_NAME
      value: logs
    - name: CASSANDRA_DATACENTER
      value: datacenter1