apiVersion: v1
kind: Service
metadata:
  name: gateway
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: gateway
  type: LoadBalancer

---
apiVersion: v1
kind: Pod
metadata:
  name: gateway
  labels:
    app: gateway
spec:
  containers:
  - name: gateway
    image: ftndevops123/gateway-service:develop
    ports:
    - containerPort: 8080
    env:
    - name: ACCOMMODATION_API_BASE_URL
      value: http://accommodation:8081
    - name: USER_API_BASE_URL
      value: http://user:8080
    - name: ALLOWED_CORS_ORIGINS
      value: https://localhost:4200/,http://localhost:4200/
    