apiVersion: v1
kind: Service
metadata:
  name: notification
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: notification
  type: ClusterIP

---
apiVersion: v1
kind: Pod
metadata:
  name: notification
  labels:
    app: notification
spec:
  containers:
  - name: notification
    image: ftndevops123/notification-service:develop
    ports:
    - containerPort: 8080
    env:
    - name: RABBITMQ_HOST
      value: rabbitmq
    - name: RABBITMQ_PORT
      value: "5672"
    - name: EMAIL_USERNAME
      value: emaildevops0@gmail.com
    - name: EMAIL_PASSWORD
      value: 'qcbk bipk ekva bksx'